language: dart
dart:
- stable
# Disabling dev builds for now since the current one is 2.0.0-dev.69.5
# - dev
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.pub-cache"
before_install:
- cd ..
- wget https://github.com/jathak/scheme_impl_skeleton/archive/master.zip
- unzip master.zip
- mv scheme_impl_skeleton-master dart_scheme_impl
- cd dart_scheme_impl
- wget -O lib/impl.dart $PRIVATE_IMPL || export NO_IMPL="-x impl"
- cd $TRAVIS_BUILD_DIR
script:
- pub run test $NO_IMPL
- pub run grinder check
- pub run dart_style:format -n --set-exit-if-changed .
- dartanalyzer --fatal-warnings --strong .
- pub run dependency_validator --ignore build_runner,build_web_compilers,sass_builder
before_deploy:
- openssl aes-256-cbc -K $encrypted_2195c966699e_key -iv $encrypted_2195c966699e_iv
  -in .travis/deploy.key.enc -out .travis/deploy.key -d
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy.key
- ssh-add .travis/deploy.key
- ssh-keyscan scheme.cs61a.org >> ~/.ssh/known_hosts
- git remote add dokku dokku@scheme.cs61a.org:scheme
- git config --global push.default simple
deploy:
  provider: script
  script: make deploy
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_DART_VERSION = "stable"
