language: dart
dart:
- stable
- dev
dart_task:
- dartanalyzer: "--fatal-warnings"
- dartfmt
before_script:
- cd ..
- wget https://github.com/jathak/scheme_impl_skeleton/archive/master.zip
- unzip master.zip
- cd scheme_impl_skeleton
- wget -O lib/impl.dart $PRIVATE_IMPL
- pub get
script:
- dart ../scheme_impl_skeleton-master/test/scm.dart
env:
  global:
    secure: h7I6sC1S7qVcxUidPZWD+SMvUqTJdcekHgJ+VG5tV0sRgc0UhvqB6H/iVKe0cmJDhKTqwACGpd7Dw7ifwgpVEfQhVWeso1N9WV4XZUfJXtNi1gHV1qCE2JhfKIkTbo/f3uiKXmmuCrlvzpKOfNqgEXNfvGynWVeEc8GZ6U/mb+j8jvepgoWBZKugSiQIBXfApCV6MyM2Nuyr6oxL1sCNjirLakSmsbpsFc+nvVn175zmytex1Z5coP52nKbmHeBQpTYa4jMLnYuitlWJ090swEUiAlTSzaISlR/gv7ITqIThLJ6rVbUBAY9a+pjdKbyIBgpLJmnqTPV+qN5aRTK9NEJDKZK//sBwRLUi3hie8LftB8cigZEfGHI5Vq0PMQabRgFSLp+Lc5JjI+MGe6TISXx1X6RgcvEV4YxzcXnaMPSl6So4sVivRtMo+UoBZDh8U9/e1GWDwqDTLYteX5QidZ/KFzTGOIBM2ZszUzTmqtwWPr9yrPL8j5XeiaBWIM1Lf7hmlfm5aDUc2AibyvvyUeZNyrFb/s4fGKkwS0EYHN3PcFAw5lSdd2eq+ZMQCk7sUUivilNMNcMgLeRbEUQoJf3DGwQaDizQrouam4wmKriEyypo+SQa7GlQFKEXTqmK87fXXeu7mQq6nFiqPtUoJcZzaJnYeLyTep6JOoAeWd8=
