name: cs61a_scheme
description: Dart implementation of 61A Scheme.
version: 2.0.0-beta
homepage: https://scheme.cs61a.org
author: Jen Thakar <jthakar@berkeley.edu>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analyzer: ^0.32.4
  markdown: ^2.0.2
  quiver: ^2.0.0+1
  tuple: ^1.0.2

dev_dependencies:
  # Implementation library
  cs61a_scheme_impl:
    path: ../dart_scheme_impl

  # Core library tools
  dart_style: any
  dependency_validator: any
  grinder: any
  test: any

  # CLI REPL
  cli_repl: ^0.2.0

  # Web app building
  sass_builder: ^2.1.1
  build_runner: any
  build_web_compilers: any
